### ISSUE TITLE
Errors are not properly forwarded when using errutil.NewErrors

### ISSUE THREAD

**Issue by mirdhyn** [tsaikd/gogstash#10]
How to reproduce:
- start gogstash with 'amqp' output with no active AMQP servers

Result:
```
2016/04/25 14:37:01 logger.go:15 [error] handle output config failed: map["exchange_type":"topic" "exchange_durable":%!q(bool=true) "exchange_auto_delete":%!q(bool=false) "persistent":%!q(bool=false) "retry_count":%!q(float64=10) "type":"amqp" "urls":["amqp://guest:guest@localhost:5672/"] "routing_key":"%{routing}" "exchange":"amq.topic"]
```

Expected result:
- Error containing `no valid amqp server connection found` (see https://github.com/tsaikd/gogstash/blob/master/output/amqp/outputamqp.go#L96)

**Comment by tsaikd** [comment]
I refine the error message handling in 804dfedaf9172f20163a2d3e4d5624d288c3fb88

Expected errors contains `ErrorGetOutputs`, `ErrorRunOutput1`, `ErrorNoValidConn`

Does it help?

**Comment by mirdhyn** [comment]
unfortunately it doesn't help... `no valid amqp server connection found` is not outputed.
I get:
```
2016/04/26 11:48:15 logger.go:15 [error] get outputs from config failed
```
instead of 
```
2016/04/26 11:48:15 logger.go:15 [error] get outputs from config failed: no valid amqp server connection found
```

I am thinking that maybe it would be better to manage logging output directly in the plugin. So it would do something like this:
```
2016/04/26 11:48:15 [error] no valid amqp server connection found
2016/04/26 11:48:15 [error] get outputs from config failed
```

What do you think?

**Comment by tsaikd** [comment]
How about 4b4a19573382d21f829ad737a6edb1963f428d85 ?
I use another error formatter (errutil.ConsoleFormatter) in tsaikd/KDGoLib@421306dbd8ce43191bad6b993f0f5523e4e30b85
It will output all errors seperated by `;`

**Comment by mirdhyn** [comment]
That's much better now :) Thank you.
