### ISSUE TITLE
use a corporate-friendly open source license

### ISSUE THREAD

**Issue by horacimacias** [tsaikd/gogstash#120]
I'm considering using gogstash on a commercial product but the current LGPL license prevents me from doing this.
Could you please consider switching to a more corporate-friendly open source license instead? e.g. MIT, Apache 2.0 and BSD tend to be fine

**Comment by tsaikd** [comment]
I'm ok to change the license to MIT, @tengattack or any other contributors have concerns?

**Comment by tengattack** [comment]
I'm also no problem to switch the license.

**Comment by tsaikd** [comment]
I will change the license to MIT if no contributors have any concerns, about 2 weeks later.

**Comment by horacimacias** [comment]
that would be great!

thanks for the fast response.

**Comment by Mizaro** [comment]
Thank you for changing the license :) It is very appreciated.
