### ISSUE TITLE
Output plugin for ClickHouse

### ISSUE THREAD

**Issue by pachico** [tsaikd/gogstash#125]
By any chance you are not thinking about adding support to ClickHouse, right?
Its API is simple http and accepts json documents.

**Comment by tsaikd** [comment]
PR is always welcomed. :)

**Comment by pachico** [comment]
I know, I know :) 
I'll try to understand the code and see if I can make it (I don't have a strong background in Go)

**Comment by yuxiaorui** [comment]
@pachico use Kafka output with [ClickHouse Kafka Engine](https://clickhouse.tech/docs/en/engines/table_engines/integrations/kafka/) can insert json documents to ClickHouse.

**Comment by pachico** [comment]
@yuxiaorui yes, I'm aware of it but I don't want to create the Kafka infrastructure just for my use cases
