### ISSUE TITLE
useragent filter should use uap-go regexes by default

### ISSUE THREAD

**Issue by edsrzf** [tsaikd/gogstash#136]
I'm trying to use the `useragent` filter and getting the error: `filter useragent 'regexes' not configured`. I would expect gogstash to default to using the `DefinitionYaml` variable [available in uap-go](https://github.com/ua-parser/uap-go/blob/e1c09f13e2fe20d591e97106ab10758f5a80f07b/uaparser/yaml.go#L3), so I don't have to configure this unless I require a different set of regexes.

I'd be happy to create PR for this if it sounds reasonable.

**Comment by tengattack** [comment]
I think it would be easier to be configured than now, it sounds reasonable.
