### ISSUE TITLE
Filter for key-value and unix nano timestamps

### ISSUE THREAD

**Issue by helgeolav** [tsaikd/gogstash#142]
Hi

I have been looking into gogstash and I like its simplicity. My use-case is receiving syslog messages from a Fortigate, parse the message and then send it to Elasticsearch. (And trying to avoid the overhead of logstash.) Logstash is also deprecating its kv filter, so for me I need another long-term solution.

There are two features I miss to be able to to this with gogstash.

1. Handling of Unix nano timestamps, as it is not supported in the date filter.
2. A filter that understand data in a key-value syntax, like "key1=data1 key2=data2". The Fortigate ships its syslogs in this format.

To solve these problems I have (re)written the code and tested that it works for me. The filter (it is called kv) takes an input string and produces values based on the content.

The unix nano timestamp issue I am a bit more unsure how to solve. I decided to add a new format "UNIXNANO" and make it handle it correctly. The alternative would be to rewrite convert/convertFloat so they can guess what unix timestamp format this is.

Is this something you are interested in and something I can add to your code. If so what way do you want me to contribute?

Below is a snippet from my configuration:
```text
    "filter": [
        {
            "type": "grok",
            "match": ["<%{NUMBER:syslog_pri}>%{GREEDYDATA:kvmessage}"]
        },
        {
            "type": "kv",
            "source": "kvmessage",
            "strings": ["tz"]
        },
        {
            "type": "date",
            "source": "eventtime",
            "format": ["UNIXNANO"]
        },
```

**Comment by tsaikd** [comment]
PR is welcomed.

**Comment by helgeolav** [comment]
#143 created. Closing this issue.
