### ISSUE TITLE
output module "http" failed

### ISSUE THREAD

**Issue by YangTao0** [tsaikd/gogstash#196]
My output:
output:
  - type: http
    urls: ["http://xxxxxxx/web_api/log_file_report"]

    http_status_codes: [200, 201, 202]
    http_error_codes: [501, 405, 404, 208, 505]
    retry_interval: 60
    max_queue_size: 1
    ignore_ssl: true

Why Log output：
2022/08/22 16:54:29 output.go:99 [error] output module "http" failed: "http://xxxxxxx/web_api/log_file_report" retryable error 200
2022/08/22 16:55:28 simplequeue.go:129 [error] queue: httpsendone "http://xxxxxxx/web_api/log_file_report" retryable error 200

**Comment by helgeolav** [comment]
I am not sure why this happens. I will have to try recreate this error, it seems like the config is parsed the wrong way. If you remove the line "http_status_codes", will it work then? (You are using the default values, so they are not neded.) Or you can try remove 200 from the status codes.

**Comment by YangTao0** [comment]
I try output config like this:
output:
  - type: http
    # (required)
    # Endpoints to publish to (one in list is random chosen)
    urls: ["http://xxxxxxx/web_api/log_file_report"]
    # HTTP status codes that indicates that message is delivered successfully, default list below
    #http_status_codes: [200, 201, 202]
    # HTTP status codes that indicates that message failed with an error where it is not possible to retry to send the
    # message, default list below
    #http_error_codes: [501, 405, 404, 208, 505]
    # How often to retry to send messages in case it was not delivered successfully, default is 30 seconds
    #retry_interval: 60

    # The maximum size of messages that can be queued (in case of delivery issues) before messages are dropped.
    # Default is one message, use -1 to not limit the queue.
    #max_queue_size: 1
    # true if you want to disable SSL/TLS validation of remote endpoint, default is false
    #ignore_ssl: true

But,the log still outputs an error message:

2022/08/23 14:55:05 output.go:99 [error] output module "http" failed: "http://xxxxxxx/web_api/log_file_report" retryable error 200
2022/08/23 14:55:35 simplequeue.go:129 [error] queue: httpsendone "http://xxxxxxx/web_api/log_file_report" retryable error 200
2022/08/23 14:56:05 simplequeue.go:129 [error] queue: httpsendone "http://xxxxxxx/web_api/log_file_report" retryable error 200
2022/08/23 14:56:35 simplequeue.go:129 [error] queue: httpsendone "http://xxxxxxx/web_api/log_file_report" retryable error 200

**Comment by tsaikd** [comment]
@helgeolav There is a bug in `MapFromInts()`

```diff
diff --git a/output/http/outputhttp.go b/output/http/outputhttp.go
index 91899ec..8a63bc3 100644
--- a/output/http/outputhttp.go
+++ b/output/http/outputhttp.go
@@ -154,7 +154,7 @@ func (t *OutputConfig) failedDelivery(ctx context.Context, event logevent.LogEve
 // MapFromInts returns a map containing all the ints in the array
 func MapFromInts(nums []int) map[int]struct{} {
        result := make(map[int]struct{}, len(nums))
-       for x := range nums {
+       for _, x := range nums {
                result[x] = struct{}{}
        }
        return result
```

**Comment by YangTao0** [comment]
func MapFromInts(nums []int) map[int]struct{} {
        result := make(map[int]struct{}, len(nums))
        //for x := range nums {
        for _, x := range nums {
                result[x] = struct{}{}
        }
        return result
Build this code ,  log error Fixed，thanks.
