### ISSUE TITLE
question: Usage with Elastic ?

### ISSUE THREAD

**Issue by joeblew99** [tsaikd/gogstash#2]
so can i use this to pump data to Elastic ?

**Comment by tsaikd** [comment]
@joeblew99 yes, I write this project because logstash is so~~ fat ...lol

gogstash can input from shell script and direct insert to elastic search or redis

**Comment by joeblew99** [comment]
There is now filebeats on the elastic repo.
It says it replaces logstash.

What do you think ?

**Comment by tsaikd** [comment]
It's a good news to hear that. Official tools for shipping log.
But currently, elastic team only release packetbeat, topbeat, filebeat.
It seems no way to run custom shell script.
Anyway, I'll try XXbeat later.

**Comment by joeblew99** [comment]
Ok :)

I am not ready yet, as am still coding other bits.
If you happen to have some success :)

There is also the pure golang option of Bleve.
It's backed by leveldb. Abit yucky.
The documentation is great.

**Comment by joeblew99** [comment]
dump question.
I have various logs as JSON, and also some CSV files that are on remote servers, and right now i just need to be able to send them up to S3, and dump them there.

Will this be able to do that ?
I can see in the examples i need to run this on its own daemon, with a config.

**Comment by tsaikd** [comment]
input module exec support JSON format
CSV is not supported yet,
output module does not support S3 yet, it's welcome to pull request for them :)

**Comment by joeblew99** [comment]
I wish I had the time. At the moment its nuts.
