### ISSUE TITLE
too many arguments in call to conf.client.BulkProcessor().Do()

### ISSUE THREAD

**Issue by R7R8** [tsaikd/gogstash#29]
github.com/tsaikd/gogstash/output/elastic/outputelastic.go:84: too many arguments in call to conf.client.BulkProcessor().Name("gogstash-output-elastic").BulkActions(conf.BulkActions).BulkSize(conf.BulkSize).FlushInterval(conf.BulkFlushInterval).Do
        have ("context".Context)
        want ()

**Comment by tsaikd** [comment]
what's your version of **gopkg.in/olivere/elastic.v5**?  
try to `go get -u -v "gopkg.in/olivere/elastic.v5"` and rebuild.

**Comment by R7R8** [comment]
It does work。Thank you very much~~
