### ISSUE TITLE
Would gogstash silent fail in elastic output?

### ISSUE THREAD

**Issue by tengattack** [tsaikd/gogstash#38]
<del>I'm using gogstash 0.1.14 as an indexer from redis to elasticsearch</del>

There are some errors in my error logs:
```txt
2018/06/19 08:25:47 output.go:52 [error] output failed: elastic: Error 429 (Too Many Requests): rejected execution of org.elasticsearch.transport.TransportService$7@3e869f6 on EsThreadPoolExecutor[name = data00/bulk, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@2ded0e49[Running, pool size = 8, active threads = 8, queued tasks = 200, completed tasks = 27481615]] [type=es_rejected_execution_exception]
```

I'm trying to find out the error came from:
https://github.com/tsaikd/gogstash/blob/binary/config/output.go#L44

However, I haven't see the event back to the event channel after it failed.
Am I missing some thing or it will just lost event data after it failed?

Thanks

**Comment by tengattack** [comment]
Oh I noticed that action changed in master branch.
It start using bulk API to output to elastic.

However, will it slient failed in latest code, because I haven't find out the error handling for the elastic's BulkProcessor
https://github.com/olivere/elastic/blob/a487785d708c8e6a99b8d498947c220511b6ec7f/bulk_processor.go#L524

**Comment by tengattack** [comment]
Great! 
BTW, could we add a backoff maximum time config for elastic output? So that I can customized the backoff action. Currently, It can only retry about 5 times (`200ms to 10000ms`) until it reach the maximum time.

**Comment by tengattack** [comment]
It will change the backoff type? Maybe we can find a way to specify the backoff type:
https://github.com/olivere/elastic/blob/a7f6620ddddaaccb6fa041eaa281182fd4b4fcc4/backoff.go

I prefer to use exponential backoff :)

**Comment by tsaikd** [comment]
There are no stop condition in ConstantBackoff and ExponentialBackoff. I mean it will retry forever, until memory full or app crash. But maybe it make sense for logging scenario. What about this?
```
	// ExponentialBackoffInitialTimeout used to set the first/minimal interval in elastic.ExponentialBackoff
	// Defaults to 10 seconds
	ExponentialBackoffInitialTimeout time.Duration `json:"exponential_backoff_initial_timeout,omitempty"`

	// ExponentialBackoffMaxTimeout used to set the maximum wait interval in elastic.ExponentialBackoff
	// Defaults to 300 seconds
	ExponentialBackoffMaxTimeout time.Duration `json:"exponential_backoff_initial_timeout,omitempty"`
```

**Comment by tengattack** [comment]
Ummm, I think ExponentialBackoff will stop when it reach the maximum timeout:
https://github.com/olivere/elastic/blob/a7f6620ddddaaccb6fa041eaa281182fd4b4fcc4/backoff.go#L91

But that's work! Thank you!

**Comment by tengattack** [comment]
BTW, the key of maximum timeout wrong?

**Comment by tengattack** [comment]
And we can add `SetErrorLog` for the elastic client or `After` callback for the BulkRequest?

**Comment by tengattack** [comment]
BTW, does type `time.Duration` support some kind of writing like `"5s"` or `"1h"`

**Comment by tsaikd** [comment]
done

**Comment by tengattack** [comment]
If we just connect the `SetErrorLog` to `config.Logger` does the error output will send to stdout instead of stderr?

**Comment by tsaikd** [comment]
I create a new error logger for it.

**Comment by tengattack** [comment]
oh! Beautiful!
Super thanks!

**Comment by tengattack** [comment]
BTW, `Logger`'s Out changed to `Stdout`, does it affected the `config.Logger.Errorf` output?

**Comment by tsaikd** [comment]
No, Logger always output to stdout, ErrorLogger always output to stderr, no matter what's the function call.

**Comment by tengattack** [comment]
I see

**Comment by tengattack** [comment]
Last question, as I trying to find out `github.com/sirupsen/logrus`'s code, I found the owner name  lowercase initials, we should correct it?
https://github.com/tsaikd/gogstash/commit/a8ad5084cc127b9255fc1c8a8a89b26333ea8ef9#diff-beaa11a399561a57ec0d693757f6afb1R6

**Comment by tsaikd** [comment]
Thanks.
Replaced with lowercase and remember to update dependent lib before rebuilding.

**Comment by tengattack** [comment]
Cheers!
