### ISSUE TITLE
elastic lib version

### ISSUE THREAD

**Issue by dzliang10** [tsaikd/gogstash#42]
can not build with "gopkg.in/olivere/elastic.v5" ,but with "gopkg.in/olivere/elastic.v6"

**Comment by tsaikd** [comment]
I build successfully with https://github.com/olivere/elastic/tree/52741dc2ce53629cbe1e673869040d886cba2cd5

what's your error message?

**Comment by dzliang10** [comment]
error:
../../../github.com/tsaikd/gogstash/output/elastic/outputelastic.go:106:40: conf.client.BulkProcessor().Name("gogstash-output-elastic").BulkActions(conf.BulkActions).BulkSize(conf.BulkSize).FlushInterval(conf.BulkFlushInterval).Backoff undefined (type *elastic.BulkProcessorService has no field or method Backoff)

it can work with:
gopkg.in/olivere/elastic.v6
